name: quote_and_joke
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  after_init: ^0.1.2
  auto_size_text: ^2.1.0
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  firebase_ml_vision: ^0.9.6+2
  get_it: ^5.0.1
  image_picker: ^0.6.7+11
  like_button: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Italic.ttf
          style: italic
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
